name: ingaz_fawry
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_screenutil:
  font_awesome_flutter:
  flutter_sequence_animation: 3.0.1
  flutter_rating_bar:
  auto_size_text:
  intl:
  firebase_core:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  file_picker:
  permission_handler:
  flutter_animated_dialog:
  data_connection_checker:
  fluttertoast:
  connectivity:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: logoFont
      fonts:
        - asset: assets/fonts/HS-Ishraq-Regular.otf
       
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

